### PR TITLE
 hardcode virtualenv@16.0.0 

### PR DESCRIPTION
**Pull request by YifeiZuo01**
## Status
**READY**

## Description
This uses hardcoded virtualenv version to fix the installation.

**Note:**  the base branch is "fix-windows" which  was used.

## issue raised for python virtualenv
https://github.com/pypa/virtualenv/issues/1240

root cause here: 
https://github.com/pypa/virtualenv/issues/1241

## jira
IOTSYSTOOL-1266:

### CODE REVIEW

**Comment by YifeiZuo01** [comment]
@jupe  maunal add Reviewers, since the button seems been disabled.

**Review by jupe — APPROVED** [review]
Please create defect over here: https://github.com/pypa/virtualenv/issues/new

changes instead seems to work now as expected.

**Comment by YifeiZuo01** [comment]
here it is: pypa/virtualenv#1240

**Comment by YifeiZuo01** [comment]
@jupe  could you please  merge and add the suitable tag? I don't have the write access.

**Pull request merged**
